### ISSUE TITLE
Convert base image to use alpine instead of ubuntu

### ISSUE THREAD

**Issue by eldadfux** [appwrite/docker-telegraf#2]
We are looking for ways to make Appwrite Docker images smaller.

**Comment by gabrielcalderon** [comment]
@eldadfux I can do this one. Should telegraf also be upgraded from 1.7 ? According to their Github, current version is 1.15.3

https://github.com/influxdata/telegraf/releases

**Comment by eldadfux** [comment]
@gabrielcalderon yes, this can be a good opportunity to upgrade versions. Just choose 1.15 alpine image from here: https://hub.docker.com/_/telegraf?tab=tags and use it as base for this repo Dockerfile.

If you'd like we have a couple more repos that we're trying to move to alpine.

**Comment by gabrielcalderon** [comment]
@eldadfux Sounds great, I will take a look at the repos tomorrow. :-)

**Comment by parshnt** [comment]
Hi @eldadfux,
If the issue is still open, I'd like to open a quick PR and would like to work on other repos as well.

**Comment by eldadfux** [comment]
@gabrielcalderon would you like to move this issue to @parshnt ? please let us know if you don't have enough time to complete it.

**Comment by gabrielcalderon** [comment]
@eldadfux It's open because Hacktoberfest starts on Oct 1st. Only PR's made in October count towards Hacktoberfest.

**Comment by eldadfux** [comment]
OK @gabrielcalderon 👌🏻

**Comment by gabrielcalderon** [comment]
@eldadfux I just submitted a PR for this issue: https://github.com/appwrite/docker-telegraf/pull/5
